artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/fullstackaaronsanchezbelber/pipe-forecast/blob/main/sales_train_merged.zip
  local_data_file: artifacts/data_ingestion/sales_train_merged.zip
  unzip_dir: artifacts/data_ingestion
